MVC5BlogProjectNTier/Controllers/AboutController.cs
using BussinessLayer.Concrete;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC5BlogProjectNTier.Controllers
{
    [AllowAnonymous]
    public class AboutController : Controller
    {
        // GET: About
        AboutManager aboutManager = new AboutManager();
        public ActionResult Index()
        {
            var aboutContent = aboutManager.GetAll();

            return View(aboutContent);
        }
        public PartialViewResult Footer()
        {

            var aboutcontentList=aboutManager.GetAll();


            return PartialView(aboutcontentList);
        }

        public PartialViewResult MeetTheTeam()
        {
            AuthorManager autman=new AuthorManager();

            var authorList=autman.GetAll();

            return PartialView(authorList);
        }
        [HttpGet]
        public ActionResult UpdateAbout()
        {
            var aboutList=aboutManager.GetAll();

            return View(aboutList);
        }

        [HttpPost]
        public ActionResult UpdateAbout(About p)
        {
            aboutManager.UpdateAboutBM(p);

            return RedirectToAction("UpdateAbout");
        }
    }
}

MVC5BlogProjectNTier/Controllers/AuthorController.cs
using BussinessLayer.Concrete;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC5BlogProjectNTier.Controllers
{
    public class AuthorController : Controller
    {
        // GET: Author
        BlogManager blogManager = new BlogManager();
        AuthorManager authorManager = new AuthorManager();
        [AllowAnonymous]
        public PartialViewResult AuthorAbout(int id)
        {
            var authordetail = blogManager.GetBlogById(id);

            return PartialView(authordetail);
        }
        [AllowAnonymous]
        public PartialViewResult AuthorPopularPost(int id)
        {
            var blogAuthorId = blogManager.GetAll().Where(x => x.BlogID == id)
                .Select(y => y.AuthorID).FirstOrDefault();
            //ViewBag.blogauthorid=blogAuthorId;

            var authorBlogs = blogManager.GetblogByauthor(blogAuthorId);

            return PartialView(authorBlogs);
        }

        public ActionResult AuthorList()
        {
            var authorLists = authorManager.GetAll();

            return View(authorLists);
        }
        [HttpGet]
        public ActionResult addAuthor()
        {
            return View();
        }

        [HttpPost]
        public ActionResult addAuthor(Author parameter)
        {
            authorManager.AddAuthorBL(parameter);
            return RedirectToAction("AuthorList");
        }
        [HttpGet]
        public ActionResult AuthorEdit(int id)
        {

            Author author = authorManager.FindAuthor(id);

            return View(author);
        }
        
        public ActionResult AuthorEdit(Author p)
        {
            authorManager.EditAuthor(p);

            return RedirectToAction("AuthorList");
        }

    }
}

MVC5BlogProjectNTier/Controllers/BlogController.cs
using BussinessLayer.Concrete;
using DataAccessLayer.Concrete;
using EntityLayer.Concrete;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC5BlogProjectNTier.Controllers
{
    public class BlogController : Controller
    {
        BlogManager blogmanager = new BlogManager();


        // GET: Blog
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        #region BlogList

        [AllowAnonymous]
        public PartialViewResult BlogList(int page = 1)
        {
            var blogllist = blogmanager.GetAll().ToPagedList(page, 6);

            return PartialView(blogllist);
        }
        #endregion
        [AllowAnonymous]
        public PartialViewResult FeaturedPost()
        {
            #region Post1
            //1. post
            var posttitle1 = blogmanager.GetAll()
                .Where(x => x.CategoryID == 1)
                .OrderByDescending(x => x.BlogID)
                .Select(x => x.BlogTitle)
                .FirstOrDefault();

            // post img1 
            var postimg1 = blogmanager.GetAll()
                .Where(x => x.CategoryID == 1)
                .OrderByDescending(x => x.BlogID)
                .Select(x => x.BlogImage)
                .FirstOrDefault();

            //blogdate1
            var postdate1 = blogmanager.GetAll()
                .Where(x => x.CategoryID == 1)
                .OrderByDescending(x => x.BlogID)
                .Select(x => x.BlogDate)
                .FirstOrDefault();
            //blogpostıd
            var blogpostid1 = blogmanager.GetAll()
                .Where(x => x.CategoryID == 1)
                .OrderByDescending(x => x.BlogID)
                .Select(x => x.BlogID)
                .FirstOrDefault();


            ViewBag.posttitle1 = posttitle1;
            ViewBag.postimg1 = postimg1;
            ViewBag.postdate1 = postdate1;
            ViewBag.blogpostid1 = blogpostid1;

            #endregion

            #region Post2
            //1. post
            var posttitle2 = blogmanager.GetAll()
                .Where(x => x.CategoryID == 2)
                .OrderByDescending(x => x.BlogID)
                .Select(x => x.BlogTitle)
                .FirstOrDefault();

            // post img1 
            var postimg2 = blogmanager.GetAll()
                .Where(x => x.CategoryID == 2)
                .OrderByDescending(x => x.BlogID)
                .Select(x => x.BlogImage)
                .FirstOrDefault();

            //blogdate1
            var postdate2 = blogmanager.GetAll()
                .Where(x => x.CategoryID == 2)
                .OrderByDescending(x => x.BlogID)
                .Select(x => x.BlogDate)
                .FirstOrDefault();
            //blogpostıd
            var blogpostid2 = blogmanager.GetAll()
                .Where(x => x.CategoryID == 2)
                .OrderByDescending(x => x.BlogID)
                .Select(x => x.BlogID)
                .FirstOrDefault();

            ViewBag.posttitle2 = posttitle2;
            ViewBag.postimg2 = postimg2;
            ViewBag.postdate2 = postdate2;
            ViewBag.blogpostid2 = blogpostid2;

            #endregion

            #region Post3
            //1. post
            var posttitle3 = blogmanager.GetAll()
                .Where(x => x.CategoryID == 3)
                .OrderByDescending(x => x.BlogID)
                .Select(x => x.BlogTitle)
                .FirstOrDefault();

            // post img1 
            var postimg3 = blogmanager.GetAll()
                .Where(x => x.CategoryID == 3)
                .OrderByDescending(x => x.BlogID)
                .Select(x => x.BlogImage)
                .FirstOrDefault();

            //blogdate1
            var postdate3 = blogmanager.GetAll()
                .Where(x => x.CategoryID == 3)
                .OrderByDescending(x => x.BlogID)
                .Select(x => x.BlogDate)
                .FirstOrDefault();
            //blogpostıd
            var blogpostid3 = blogmanager.GetAll()
                .Where(x => x.CategoryID == 3)
                .OrderByDescending(x => x.BlogID)
                .Select(x => x.BlogID)
                .FirstOrDefault();

            
            ViewBag.blogpostid3 = blogpostid3;
            ViewBag.posttitle3 = posttitle3;
            ViewBag.postimg3 = postimg3;
            ViewBag.postdate3 = postdate3;

            #endregion

            #region Post4
            //1. post
            var posttitle4 = blogmanager.GetAll()
                .Where(x => x.CategoryID == 4)
                .OrderByDescending(x => x.BlogID)
                .Select(x => x.BlogTitle)
                .FirstOrDefault();

            // post img1 
            var postimg4 = blogmanager.GetAll()
                .Where(x => x.CategoryID == 4)
                .OrderByDescending(x => x.BlogID)
                .Select(x => x.BlogImage)
                .FirstOrDefault();

            //blogdate1
            var postdate4 = blogmanager.GetAll()
                .Where(x => x.CategoryID == 4)
                .OrderByDescending(x => x.BlogID)
                .Select(x => x.BlogDate)
                .FirstOrDefault();

            ViewBag.posttitle4 = posttitle4;
            ViewBag.postimg4 = postimg4;
            ViewBag.postdate4 = postdate4;
            //blogpostıd
            var blogpostid4 = blogmanager.GetAll()
                .Where(x => x.CategoryID == 4)
                .OrderByDescending(x => x.BlogID)
                .Select(x => x.BlogID)
                .FirstOrDefault();

            ViewBag.blogpostid2 = blogpostid4;

            #endregion

            #region Post4
            //1. post
            var posttitle5 = blogmanager.GetAll()
                .Where(x => x.CategoryID == 5)
                .OrderByDescending(x => x.BlogID)
                .Select(x => x.BlogTitle)
                .FirstOrDefault();

            // post img1 
            var postimg5 = blogmanager.GetAll()
                .Where(x => x.CategoryID == 5)
                .OrderByDescending(x => x.BlogID)
                .Select(x => x.BlogImage)
                .FirstOrDefault();

            //blogdate1
            var postdate5 = blogmanager.GetAll()
                .Where(x => x.CategoryID == 5)
                .OrderByDescending(x => x.BlogID)
                .Select(x => x.BlogDate)
                .FirstOrDefault();

            ViewBag.posttitle5 = posttitle5;
            ViewBag.postimg5 = postimg5;
            ViewBag.postdate5 = postdate5;
            //blogpostıd
            var blogpostid5 = blogmanager.GetAll()
                .Where(x => x.CategoryID == 5)
                .OrderByDescending(x => x.BlogID)
                .Select(x => x.BlogID)
                .FirstOrDefault();

            
            ViewBag.blogpostid5 = blogpostid5;

            #endregion

            return PartialView();
        }
        [AllowAnonymous]
        public PartialViewResult OtherFuturedPost()
        {
            return PartialView();
        }


        [AllowAnonymous]
        public ActionResult BlogDetails()
        {

            return View();
        }
        [AllowAnonymous]
        public PartialViewResult BlogCover(int id)
        {
            var blogdetaillist = blogmanager.GetBlogById(id);

            return PartialView(blogdetaillist);
        }
        [AllowAnonymous]
        public PartialViewResult BlogReadAll(int id)
        {
            var BlogDetailsList = blogmanager.GetBlogById(id);
            return PartialView(BlogDetailsList);
        }
        [AllowAnonymous]
        public ActionResult BlogByCategory(int id)
        {
            var BlogListByCategory = blogmanager.GetBlogById(id);

            var categoryname = blogmanager.GetBlogById(id).Select(x => x.Categories.CategoryName).FirstOrDefault();
            ViewBag.categoryName = categoryname;

            var categoryDesc = blogmanager.GetBlogById(id).Select(x => x.Categories.CategoryDescription).FirstOrDefault();
            ViewBag.categorydesc = categoryDesc;

            return View(BlogListByCategory);
        }
       
        public ActionResult AdminBlogList()
        {
            var bloglist = blogmanager.GetAll();

            return View(bloglist);
        }

        public ActionResult AdminBlogList2()
        {
            var bloglist = blogmanager.GetAll();
            return View(bloglist);
        }

        [HttpGet]
        public ActionResult AddNewBlog()
        {
            Context c = new Context();
            List<SelectListItem> values = (from x in c.Categories.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CategoryName,
                                               Value = x.CategoryID.ToString()
                                           }).ToList();

            ViewBag.val = values;


            List<SelectListItem> values2 = (from x in c.Authors.ToList()
                                            select new SelectListItem
                                            {
                                                Text = x.AuthorNameSurname,
                                                Value = x.AuthorID.ToString()
                                            }).ToList();
            ViewBag.val2 = values2;


            return View();
        }
        [HttpPost]
        public ActionResult AddNewBlog(Blog bloginstance)
        {
            blogmanager.BlogAddBL(bloginstance);

            return RedirectToAction("AdminBlogList");
        }


        public ActionResult DeleteBlog(int id)
        {
            blogmanager.DeleteBlogBL(id);
            return RedirectToAction("AdminBlogList");
        }
        [HttpGet]
        public ActionResult UpdateBlog(int id)
        {

MVC5BlogProjectNTier/Controllers/CategoryController.cs
using BussinessLayer.Concrete;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC5BlogProjectNTier.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        CategoryManager cm = new CategoryManager();
        public ActionResult Index()
        {
            var categoryValues = cm.GetAll();
            return View(categoryValues);
        }
        [AllowAnonymous]
        public PartialViewResult BlogDetailsCategoryList()
        {
            var categoryValues = cm.GetAll();
            return PartialView(categoryValues);
        }

        public ActionResult AdminCategoryList()
        {
            var categoryList = cm.GetAll();

            return View(categoryList);
        }
        [HttpGet]
        public ActionResult AdminCategoryAdd()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AdminCategoryAdd(Categories c)
        {
            cm.CategoryAddBBL(c);
            return RedirectToAction("AdminCategoryList");
        }


        [HttpGet]
        public ActionResult CategoryEdit(int id)
        {

            Categories category = cm.FindCategory(id);

            return View(category);
        }
        [HttpPost]
        public ActionResult CategoryEdit(Categories p)
        {
            cm.EditCategory(p);

            return RedirectToAction("AdminCategoryList");
        }

        public ActionResult CategoryDelete(int id)
        {
            cm.DeleteCategoryBL(id);
            return RedirectToAction("AdminCategoryList");
        }

        public ActionResult CategoryStatusTrue(int id)
        {
            cm.DeleteStatusTrueBL(id);
            return RedirectToAction("AdminCategoryList");
        }
    }
}

MVC5BlogProjectNTier/Controllers/CommentController.cs
using BussinessLayer.Concrete;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC5BlogProjectNTier.Controllers
{
    public class CommentController : Controller
    {
        // GET: Comment

        CommentManager commandmanager = new CommentManager();
        [AllowAnonymous]
        public PartialViewResult CommentList(int id)
        {
            var commentlist = commandmanager.CommentByBlog(id);
            return PartialView(commentlist);

        }
        [HttpGet]
        [AllowAnonymous]
        public PartialViewResult LeaveAComment( int id)
        {
            ViewBag.id=id;
            return PartialView();
        }

        [HttpPost]
        [AllowAnonymous]
        public PartialViewResult LeaveAComment(Comments c)
        {
            c.CommentStatus = true;
            commandmanager.CommentAdd(c);
            return PartialView();
        }

        public ActionResult AdminCommentListTrue()
        {
            var comment_List= commandmanager.CommentByStatusTrue();

            return View(comment_List);
        }

        public ActionResult CommentStatusChangeToFalseAction(int id)
        {
            commandmanager.ChangeCommentStatusToFalse(id);

            return RedirectToAction("AdminCommentListTrue");
        }
        public ActionResult CommentStatusChangeToTrueAction(int id)
        {
            commandmanager.ChangeCommentStatusToFalse(id);

            return RedirectToAction("AdminCommentListFalse");
        }

        public ActionResult AdminCommentListFalse()
        {
            var commentList = commandmanager.CommentStatusFalse();
            return View(commentList);
        }

    }
}

MVC5BlogProjectNTier/Views/Blog/AddNewBlog.cshtml
@model  EntityLayer.Concrete.Blog



@{
    ViewBag.Title = "AddNewBlog";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<form class="form-horizontal" method="post">
    <div class="form-group">
        @Html.Label("Blog Başlığı", new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.BlogTitle, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Blog Kategori", new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
           @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.val, new {@class="form-control"})
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Resim Yolu", new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.BlogImage, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Tarih", new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.BlogDate, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Blog Yazar", new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.DropDownListFor(x => x.AuthorID, (List<SelectListItem>)ViewBag.val2, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Blog İçerik", new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextAreaFor(x => x.BlogContent, 10, 50, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-info">Kaydet</button>
        </div>
    </div>
</form>

MVC5BlogProjectNTier/Views/Blog/AdminBlogList.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>
@{
    ViewBag.Title = "AdminBlogList";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Blog Listesi</h2>

<br />

<table class=" table table-bordered"> 
    <tr>
        <th>ID</th>
        <th>Başlık</th>
        <th>Kategori</th>
        <th>Tarih</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
        <th>Yorumlar</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.BlogID</td>
            <td>@item.BlogTitle</td>
            <td>@item.Categories.CategoryName</td>
            <td>@item.BlogDate.ToShortDateString()</td>
            <td><a href="/Blog/DeleteBlog/@item.BlogID/" class="btn btn-danger">Sil</a></td>
            <td><a href="/Blog/UpdateBlog/@item.BlogID/" class="btn btn-success">Güncelle</a></td>
            <td><a href="/Blog/BlogDetails/@item.BlogID/" class="btn btn-info">Detaylar</a></td>
            <td><a href="/Blog/GetCommentById/@item.BlogID/" class="btn btn-dark">Yorumlar</a></td>
        </tr>
    }
</table>

<a href="/Blog/AddNewBlog/" class="btn btn-primary">Yeni Ekle</a>

MVC5BlogProjectNTier/Views/Blog/AdminBlogList2.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>
@{
    ViewBag.Title = "AdminBlogList2";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<!DOCTYPE html>

<html>



<body class="hold-transition sidebar-mini">
    <section class="content">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">BLOG Listesi</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>

                            <th style="width: 1%">
                              
                                ID
                            </th>

                            <th style="width: 24%">

                                BLOG BAŞLIK

                            </th>

                            <th style="width: 10%">

                                YAZAR

                            </th>

                            <th>

                               BEĞENİ ORANI

                            </th>

                            <th style="width: 4%" class="text-center">

                                KATEGORİ
                            </th>

                            <th style="width: 20%">

                            </th>

                        </tr>

                    </thead>

                    <tbody>
                        @foreach (var i in Model)
                        {


                            <tr>

                                <td>@i.BlogID</td>
                                <td>@i.BlogTitle</td>
                                <td>

                                    <ul class="list-inline">
                                        <li><small>@i.Author.AuthorNameSurname</small></li>
                                        <li class="list-inline-item">

                                            <img alt="Avatar" class="table-avatar" src="@i.BlogImage">

                                        </li>

                                        <li class="list-inline-item">

                                            <img alt="Avatar" class="table-avatar" src="@i.Author.AuthorImage">

                                        </li>

                                        @*<li class="list-inline-item">

                                            <img alt="Avatar" class="table-avatar" src="/AdminLTE-3.0.4/dist/img/avatar3.png">

                                        </li>*@

                                    </ul>

                                </td>

                                <td class="project_progress">

                                    <div class="progress progress-sm">

                                        <div class="progress-bar bg-green" role="progressbar" aria-volumenow="57" aria-volumemin="0" aria-volumemax="100" style="width: 57%">

                                        </div>

                                    </div>

                                    <small>

                                        57% Complete

                                    </small>

                                </td>

                                <td class="project-state">

                                    <span class="badge badge-success">@i.Categories.CategoryName</span>

                                </td>

                                <td class="project-actions text-right">

                                    <a class="btn btn-primary btn-sm" href="/Blog/BlogReadAll/@i.BlogID/">

                                        <i class="fas fa-folder">

                                        </i>

                                        Sitede Gör

                                    </a>

                                    <a class="btn btn-info btn-sm" href="/Blog/UpdateBlog/@i.BlogID/">

                                        <i class="fas fa-pencil-alt">

                                        </i>

                                        Düzenle

                                    </a>

                                    <a class="btn btn-danger btn-sm" href="/Blog/DeleteBlog/@i.BlogID/">

                                        <i class="fas fa-trash">

                                        </i>

                                        Sil

                                    </a>

                                </td>

                            </tr>
                        }
                    </tbody>

                </table>

            </div>
        </div>
    </section>
</body>

</html>

MVC5BlogProjectNTier/Views/Blog/BlogByCategory.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>
@{
    ViewBag.Title = "BlogByCategory";
    Layout = "~/Views/Shared/Layout.cshtml";
}


<div class="py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <span>Category</span>

                
                    <h3>@ViewBag.categoryName</h3>
                    <p>@ViewBag.categorydesc</p>

                

            </div>
        </div>
    </div>
</div>
<div class="site-section bg-white">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-lg-4 mb-4">
                    <div class="entry2">
                        <a href="/Blog/BlogDetails/@item.BlogID"><img src="@item.BlogImage " alt="Image" class="img-fluid rounded"></a>
                        <div class="excerpt">
                            <span class="post-category text-white bg-secondary mb-3">@item.Categories.CategoryName</span>

                            <h2><a href="/Blog/BlogDetails/@item.BlogID">@item.BlogTitle</a></h2>
                            <div class="post-meta align-items-center text-left clearfix">
                                <figure class="author-figure mb-0 mr-3 float-left"><img src="@item.Author.AuthorImage" alt="Image" class="img-fluid"></figure>
                                <span class="d-inline-block mt-1">By <a href="#">@item.Author.AuthorNameSurname</a></span>
                                <span>&nbsp;-&nbsp; @(((DateTime)item.BlogDate).ToString("dd-MMM-yyyy"))</span>
                            </div>

                            <p> @item.BlogContent.Substring(0,item.BlogContent.Substring(0,200).LastIndexOf(" "))...</p>
                            <p><a href="#">Read More</a></p>
                        </div>
                    </div>
                </div>
            }



        </div>
        
    </div>
</div>
@Html.Action("Footer", "About")

MVC5BlogProjectNTier/Views/Blog/BlogCover.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>
@foreach (var item in Model)
{
    <div class="site-cover site-cover-sm same-height overlay single-page" style="background-image: url('images/img_2.jpg');">
        <div class="container">
            <div class="row same-height justify-content-center">
                <div class="col-md-12 col-lg-10">
                    <div class="post-entry text-center">
                        <span class="post-category text-white bg-success mb-3">@item.Categories.CategoryName </span>
                        <h1 class="mb-4"><a href="#">@item.BlogTitle</a></h1>
                        <div class="post-meta align-items-center text-center">
                            <figure class="author-figure mb-0 mr-3 d-inline-block"><img src="@item.BlogImage" alt="Image" class="img-fluid"></figure>
                            <span class="d-inline-block mt-1">@item.Author.AuthorNameSurname</span>
                            <span>&nbsp;-&nbsp;@(((DateTime)item.BlogDate).ToString("dd-MMM-yyyy")) </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

MVC5BlogProjectNTier/Views/Blog/BlogDetails.cshtml
@{
    ViewBag.Title = "BlogDetails";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@Html.Action("BlogCover", "Blog")
 
<section class="site-section py-lg">
    <div class="container">

        <div class="row blog-entries element-animate">

            <div class="col-md-12 col-lg-8 main-content">
                @Html.Action("BlogReadAll", "Blog")


                @Html.Action("CommentList", "Comment")

            </div>

            <div class="col-md-12 col-lg-4 sidebar">
                @Html.Action("AuthorAbout", "Author")

                @Html.Action("AuthorPopularPost", "Author")

                @Html.Action("BlogDetailsCategoryList", "Category")
            </div>


        </div>
    </div>
</section>

@Html.Action("AddMail", "MailSubscribe")
@Html.Action("Footer", "About")

MVC5BlogProjectNTier/Views/Blog/BlogReadAll.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>

@foreach (var x in Model)
{
    <div class="post-content-body">
        <p>@x.BlogContent</p>
        <div class="row mb-5 mt-5">
            <div class="col-md-12 mb-4">
                <img src="@x.BlogImage" alt="Image placeholder" class="img-fluid rounded">
            </div>

        </div>

    </div>
}

MVC5BlogProjectNTier/Views/Blog/GetCommentById.cshtml
@model IEnumerable<EntityLayer.Concrete.Comments>
@{
    ViewBag.Title = "GetCommentById";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}



<!DOCTYPE html>

<html>

<body class="hold-transition sidebar-mini">

    <div class="wrapper">

        <section class="content">

            <div class="container-fluid">

                <div class="row">

                    <div class="col-md-12">
                        <div class="timeline">
                            @foreach (var i in Model)
                            {


                                <div class="time-label">

                                    <span class="bg-green">@(((DateTime)i.CommentDate).ToString("dd-MMM-yyyy"))</span>

                                </div>
                                <div>

                                    <i class="fas fa-comment bg-yellow"></i>

                                    <div class="timeline-item">


                                        <h3 class="timeline-header"><a href="#">@i.UserName</a> @i.Mail</h3>

                                        <div class="timeline-body">
                                            @i.CommentText
                                            
                                        </div>

                                        <div class="timeline-footer">

                                            <a class="btn btn-primary btn-sm">Detaylar</a>
                                            <a class="btn btn-danger btn-sm">Kaldır</a>

                                        </div>

                                    </div>

                                </div>
                            }
                        </div>

                    </div>

                </div>

            </div>
        </section>
    </div>


</body>

</html>

MVC5BlogProjectNTier/Views/Blog/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@Html.Action("FeaturedPost","Blog")
@Html.Action("BlogList","Blog")
@*@Html.Action("OtherFuturedPost","Blog")*@
@Html.Action("AddMail","MailSubscribe")
@Html.Action("Footer","About")